// propertifi-frontend/nextjs-app/src/app/components/calculators/ROICalculator.tsx

'use client';

import React, { useState, useMemo } from 'react';
import { useForm } from 'react-hook-form';
import ROIChart from './ROIChart';
import CashFlowChart from './CashFlowChart';

const ROICalculator = () => {
  const { register, watch } = useForm();
  const [results, setResults] = useState<any>(null);

  const calculateROI = (data: any) => {
    const { purchasePrice, downPayment, interestRate, loanTerm, monthlyRent, vacancyRate, propertyTaxes, insurance, hoaFees, maintenance, propertyManagementFee } = data;

    const loanAmount = purchasePrice - downPayment;
    const monthlyInterestRate = interestRate / 100 / 12;
    const numberOfPayments = loanTerm * 12;
    const monthlyMortgage = loanAmount * (monthlyInterestRate * Math.pow(1 + monthlyInterestRate, numberOfPayments)) / (Math.pow(1 + monthlyInterestRate, numberOfPayments) - 1);

    const grossIncome = monthlyRent * 12;
    const vacancyLoss = grossIncome * (vacancyRate / 100);
    const effectiveGrossIncome = grossIncome - vacancyLoss;

    const totalExpenses = (propertyTaxes / 12 + insurance / 12 + hoaFees + maintenance + (monthlyRent * (propertyManagementFee / 100))) * 12;
    const netOperatingIncome = effectiveGrossIncome - totalExpenses;

    const cashFlow = netOperatingIncome - (monthlyMortgage * 12);
    const cashOnCashReturn = (cashFlow / downPayment) * 100;
    const capRate = (netOperatingIncome / purchasePrice) * 100;

    setResults({
      monthlyMortgage: monthlyMortgage.toFixed(2),
      netOperatingIncome: netOperatingIncome.toFixed(2),
      cashFlow: cashFlow.toFixed(2),
      cashOnCashReturn: cashOnCashReturn.toFixed(2),
      capRate: capRate.toFixed(2),
      chartData: {
        roi: {
          labels: ['Cash on Cash Return', 'Cap Rate'],
          datasets: [
            {
              label: 'ROI',
              data: [cashOnCashReturn, capRate],
              backgroundColor: ['rgba(54, 162, 235, 0.2)', 'rgba(255, 99, 132, 0.2)'],
            },
          ],
        },
        cashFlow: {
          labels: Array.from({ length: loanTerm }, (_, i) => `Year ${i + 1}`),
          datasets: [
            {
              label: 'Cash Flow',
              data: Array.from({ length: loanTerm }, (_, i) => cashFlow * (i + 1)),
              borderColor: 'rgb(75, 192, 192)',
              backgroundColor: 'rgba(75, 192, 192, 0.2)',
            },
          ],
        },
      },
    });
  };

  const formData = watch();

  useMemo(() => {
    calculateROI(formData);
  }, [formData]);

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div className="bg-white shadow-lg rounded-lg p-6">
        <h3 className="text-xl font-semibold mb-4">Calculator Inputs</h3>
        <form className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700">Purchase Price</label>
            <input type="number" {...register('purchasePrice', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Down Payment</label>
            <input type="number" {...register('downPayment', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Interest Rate (%)</label>
            <input type="number" {...register('interestRate', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Loan Term (years)</label>
            <input type="number" {...register('loanTerm', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Monthly Rent</label>
            <input type="number" {...register('monthlyRent', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Vacancy Rate (%)</label>
            <input type="number" {...register('vacancyRate', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Property Taxes (annual)</label>
            <input type="number" {...register('propertyTaxes', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Insurance (annual)</label>
            <input type="number" {...register('insurance', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">HOA Fees (monthly)</label>
            <input type="number" {...register('hoaFees', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Maintenance (monthly)</label>
            <input type="number" {...register('maintenance', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700">Property Management Fee (%)</label>
            <input type="number" {...register('propertyManagementFee', { valueAsNumber: true })} className="mt-1 block w-full rounded-md border-gray-300 shadow-sm" />
          </div>
        </form>
      </div>
      <div className="space-y-8">
        <div className="bg-white shadow-lg rounded-lg p-6">
          <h3 className="text-xl font-semibold mb-4">Results</h3>
          {results && (
            <div className="space-y-2">
              <p><strong>Monthly Mortgage:</strong> ${results.monthlyMortgage}</p>
              <p><strong>Net Operating Income:</strong> ${results.netOperatingIncome}</p>
              <p><strong>Cash Flow:</strong> ${results.cashFlow}</p>
              <p><strong>Cash on Cash Return:</strong> {results.cashOnCashReturn}%</p>
              <p><strong>Cap Rate:</strong> {results.capRate}%</p>
            </div>
          )}
        </div>
        {results && (
          <div className="bg-white shadow-lg rounded-lg p-6">
            <ROIChart data={results.chartData.roi} />
          </div>
        )}
        {results && (
          <div className="bg-white shadow-lg rounded-lg p-6">
            <CashFlowChart data={results.chartData.cashFlow} />
          </div>
        )}
      </div>
    </div>
  );
};

export default ROICalculator;

// angular-app/src/app/features/public/calculators/roi-calculator/roi-calculator.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { CalculatorService } from '../../../../core/services/calculator.service';
import { RoiResult } from '../../../../core/models/calculator.model';
import { UiButtonComponent } from '../../../../shared/components/ui-button/ui-button.component';

@Component({
    selector: 'app-roi-calculator',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, UiButtonComponent],
    templateUrl: './roi-calculator.component.html'
})
export class RoiCalculatorComponent {
    roiForm: FormGroup;
    result: RoiResult | null = null;
    loading = false;

    constructor(
        private fb: FormBuilder,
        private calculatorService: CalculatorService
    ) {
        this.roiForm = this.fb.group({
            purchasePrice: [300000, [Validators.required, Validators.min(0)]],
            downPayment: [60000, [Validators.required, Validators.min(0)]],
            interestRate: [6.5, [Validators.required, Validators.min(0)]],
            loanTerm: [30, [Validators.required, Validators.min(1)]],
            monthlyRent: [2500, [Validators.required, Validators.min(0)]],
            propertyTax: [3600, [Validators.required, Validators.min(0)]],
            insurance: [1200, [Validators.required, Validators.min(0)]],
            maintenance: [1000, [Validators.required, Validators.min(0)]],
            vacancyRate: [5, [Validators.required, Validators.min(0), Validators.max(100)]],
            managementFee: [10, [Validators.required, Validators.min(0), Validators.max(100)]]
        });
    }

    calculate() {
        if (this.roiForm.valid) {
            this.loading = true;
            this.calculatorService.calculateRoi(this.roiForm.value).subscribe({
                next: (res: RoiResult) => {
                    this.result = res;
                    this.loading = false;
                },
                error: (err: unknown) => {
                    console.error('Error calculating ROI', err);
                    this.loading = false;
                }
            });
        }
    }
}

<div class="bg-white">
    <div class="max-w-7xl mx-auto py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
        <div class="text-center mb-12">
            <h1 class="text-3xl font-extrabold text-gray-900 sm:text-4xl font-heading">
                ROI Calculator
            </h1>
            <p class="mt-4 text-lg text-gray-500">
                Analyze your property investment potential.
            </p>
        </div>

        <div class="lg:grid lg:grid-cols-2 lg:gap-8">
            <!-- Input Form -->
            <div class="bg-surface-50 p-6 rounded-lg shadow-sm">
                <h2 class="text-lg font-medium text-gray-900 mb-6">Property Details</h2>
                <form [formGroup]="roiForm" (ngSubmit)="calculate()" class="space-y-6">
                    <div class="grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-2">
                        <div>
                            <label for="purchasePrice" class="block text-sm font-medium text-gray-700">Purchase Price
                                ($)</label>
                            <input type="number" formControlName="purchasePrice" id="purchasePrice"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="downPayment" class="block text-sm font-medium text-gray-700">Down Payment
                                ($)</label>
                            <input type="number" formControlName="downPayment" id="downPayment"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="interestRate" class="block text-sm font-medium text-gray-700">Interest Rate
                                (%)</label>
                            <input type="number" formControlName="interestRate" id="interestRate" step="0.1"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="loanTerm" class="block text-sm font-medium text-gray-700">Loan Term
                                (Years)</label>
                            <input type="number" formControlName="loanTerm" id="loanTerm"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="monthlyRent" class="block text-sm font-medium text-gray-700">Monthly Rent
                                ($)</label>
                            <input type="number" formControlName="monthlyRent" id="monthlyRent"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="propertyTax" class="block text-sm font-medium text-gray-700">Annual Property Tax
                                ($)</label>
                            <input type="number" formControlName="propertyTax" id="propertyTax"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="insurance" class="block text-sm font-medium text-gray-700">Annual Insurance
                                ($)</label>
                            <input type="number" formControlName="insurance" id="insurance"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                        <div>
                            <label for="maintenance" class="block text-sm font-medium text-gray-700">Annual Maintenance
                                ($)</label>
                            <input type="number" formControlName="maintenance" id="maintenance"
                                class="mt-1 block w-full shadow-sm focus:ring-primary focus:border-primary border-gray-300 rounded-md">
                        </div>
                    </div>

                    <app-ui-button type="submit" variant="primary" [loading]="loading" [disabled]="roiForm.invalid"
                        class="w-full">
                        Calculate ROI
                    </app-ui-button>
                </form>
            </div>

            <!-- Results -->
            <div class="mt-8 lg:mt-0 bg-white p-6 rounded-lg shadow-lg border border-gray-100">
                <h2 class="text-lg font-medium text-gray-900 mb-6">Investment Analysis</h2>

                <div *ngIf="!result && !loading" class="text-center py-12 text-gray-500">
                    Enter property details to see the analysis.
                </div>

                <div *ngIf="result" class="space-y-8">
                    <div class="grid grid-cols-2 gap-4">
                        <div class="bg-surface-50 p-4 rounded-lg text-center">
                            <dt class="text-sm font-medium text-gray-500 truncate">Cash on Cash ROI</dt>
                            <dd class="mt-1 text-3xl font-semibold text-primary">{{ result.cashOnCashRoi |
                                number:'1.2-2' }}%</dd>
                        </div>
                        <div class="bg-surface-50 p-4 rounded-lg text-center">
                            <dt class="text-sm font-medium text-gray-500 truncate">Cap Rate</dt>
                            <dd class="mt-1 text-3xl font-semibold text-secondary">{{ result.capRate | number:'1.2-2'
                                }}%</dd>
                        </div>
                    </div>

                    <div class="border-t border-gray-200 pt-6">
                        <dl class="space-y-4">
                            <div class="flex justify-between">
                                <dt class="text-sm text-gray-500">Monthly Income</dt>
                                <dd class="text-sm font-medium text-gray-900">{{ result.monthlyIncome | currency }}</dd>
                            </div>
                            <div class="flex justify-between">
                                <dt class="text-sm text-gray-500">Monthly Expenses</dt>
                                <dd class="text-sm font-medium text-error">{{ result.monthlyExpenses | currency }}</dd>
                            </div>
                            <div class="flex justify-between border-t border-gray-100 pt-4">
                                <dt class="text-base font-medium text-gray-900">Monthly Cash Flow</dt>
                                <dd class="text-base font-bold" [class.text-success]="result.cashFlow > 0"
                                    [class.text-error]="result.cashFlow < 0">
                                    {{ result.cashFlow | currency }}
                                </dd>
                            </div>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
