// angular-app/src/app/features/public/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { UiButtonComponent } from '../../../shared/components/ui-button/ui-button.component';
import { UiInputComponent } from '../../../shared/components/ui-input/ui-input.component';

@Component({
    selector: 'app-contact',
    standalone: true,
    imports: [CommonModule, ReactiveFormsModule, UiButtonComponent, UiInputComponent],
    templateUrl: './contact.component.html'
})
export class ContactComponent {
    contactForm: FormGroup;
    isSubmitting = false;
    submitted = false;

    constructor(private fb: FormBuilder) {
        this.contactForm = this.fb.group({
            name: ['', Validators.required],
            email: ['', [Validators.required, Validators.email]],
            subject: ['', Validators.required],
            message: ['', Validators.required]
        });
    }

    onSubmit() {
        if (this.contactForm.valid) {
            this.isSubmitting = true;
            // Simulate API call
            setTimeout(() => {
                this.isSubmitting = false;
                this.submitted = true;
                this.contactForm.reset();
            }, 1500);
        } else {
            this.contactForm.markAllAsTouched();
        }
    }
}

<div class="bg-white py-16 px-4 overflow-hidden sm:px-6 lg:px-8 lg:py-24">
    <div class="relative max-w-xl mx-auto">
        <div class="text-center">
            <h2 class="text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl font-heading">
                Contact Us
            </h2>
            <p class="mt-4 text-lg leading-6 text-gray-500">
                Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.
            </p>
        </div>
        <div class="mt-12">
            <div *ngIf="submitted" class="rounded-md bg-green-50 p-4 mb-8 animate-fade-in">
                <div class="flex">
                    <div class="flex-shrink-0">
                        <!-- Heroicon name: solid/check-circle -->
                        <svg class="h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                            fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                clip-rule="evenodd" />
                        </svg>
                    </div>
                    <div class="ml-3">
                        <h3 class="text-sm font-medium text-green-800">
                            Message sent successfully
                        </h3>
                        <div class="mt-2 text-sm text-green-700">
                            <p>
                                Thank you for contacting us. We will get back to you shortly.
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <form [formGroup]="contactForm" (ngSubmit)="onSubmit()"
                class="grid grid-cols-1 gap-y-6 sm:grid-cols-2 sm:gap-x-8">
                <div class="sm:col-span-2">
                    <app-ui-input label="Name" formControlName="name" placeholder="John Doe"
                        [error]="contactForm.get('name')?.invalid && contactForm.get('name')?.touched ? 'Name is required' : ''">
                    </app-ui-input>
                </div>
                <div class="sm:col-span-2">
                    <app-ui-input label="Email" type="email" formControlName="email" placeholder="john@example.com"
                        [error]="contactForm.get('email')?.invalid && contactForm.get('email')?.touched ? 'Valid email is required' : ''">
                    </app-ui-input>
                </div>
                <div class="sm:col-span-2">
                    <app-ui-input label="Subject" formControlName="subject" placeholder="How can we help?"
                        [error]="contactForm.get('subject')?.invalid && contactForm.get('subject')?.touched ? 'Subject is required' : ''">
                    </app-ui-input>
                </div>
                <div class="sm:col-span-2">
                    <label for="message" class="block text-sm font-medium text-gray-700">Message</label>
                    <div class="mt-1">
                        <textarea id="message" formControlName="message" rows="4"
                            class="py-3 px-4 block w-full shadow-sm focus:ring-primary focus:border-primary border border-gray-300 rounded-md"
                            [class.border-red-300]="contactForm.get('message')?.invalid && contactForm.get('message')?.touched"></textarea>
                    </div>
                    <p *ngIf="contactForm.get('message')?.invalid && contactForm.get('message')?.touched"
                        class="mt-2 text-sm text-red-600">
                        Message is required
                    </p>
                </div>
                <div class="sm:col-span-2">
                    <app-ui-button type="submit" variant="primary" size="lg" [fullWidth]="true"
                        [loading]="isSubmitting">
                        Send Message
                    </app-ui-button>
                </div>
            </form>
        </div>
    </div>
</div>

// propertifi-frontend/nextjs-app/app/components/landing/Contact.tsx
'use client';

import React, { useState } from 'react';
import { apiClient } from '@/lib/api';

const Contact: React.FC = () => {
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    mobile: '',
    message: '',
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitStatus, setSubmitStatus] = useState<{
    type: 'success' | 'error' | null;
    message: string;
  }>({ type: null, message: '' });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setSubmitStatus({ type: null, message: '' });

    try {
      await apiClient.post('/contact/save', formData);

      setSubmitStatus({
        type: 'success',
        message: 'Thank you for your message! We\'ll get back to you soon.',
      });

      // Reset form
      setFormData({
        name: '',
        email: '',
        mobile: '',
        message: '',
      });
    } catch (error: any) {
      console.error('Contact form error:', error);
      setSubmitStatus({
        type: 'error',
        message: error.response?.data?.message || 'Failed to send message. Please try again.',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <section className="bg-propertifi-blue py-20" id="contact">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid md:grid-cols-2 gap-12 items-center">
          <div className="text-white">
            <h2 className="text-4xl md:text-5xl font-extrabold">Where to reach us</h2>
            <div className="mt-8 space-y-4">
              <p className="text-2xl font-bold">916-250-1264</p>
              <p className="text-lg text-white/80">Monday - Friday, 9am to 5pm PST</p>
            </div>
            <div className="mt-4">
              <a href="mailto:help@propertifi.co" className="text-2xl font-bold hover:underline">
                help@propertifi.co
              </a>
            </div>
          </div>
          <div>
            <form className="space-y-6" onSubmit={handleSubmit}>
              {submitStatus.type && (
                <div
                  className={`p-4 rounded-lg ${
                    submitStatus.type === 'success'
                      ? 'bg-green-100 text-green-800'
                      : 'bg-red-100 text-red-800'
                  }`}
                >
                  {submitStatus.message}
                </div>
              )}

              <div>
                <label htmlFor="name" className="text-white font-semibold block mb-2">
                  Your Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  required
                  disabled={isSubmitting}
                  className="w-full p-3 rounded-lg bg-white/90 text-gray-800 focus:outline-none focus:ring-2 focus:ring-propertifi-orange disabled:opacity-50"
                />
              </div>
              <div>
                <label htmlFor="email" className="text-white font-semibold block mb-2">
                  Your Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  required
                  disabled={isSubmitting}
                  className="w-full p-3 rounded-lg bg-white/90 text-gray-800 focus:outline-none focus:ring-2 focus:ring-propertifi-orange disabled:opacity-50"
                />
              </div>
              <div>
                <label htmlFor="mobile" className="text-white font-semibold block mb-2">
                  Your Phone Number
                </label>
                <input
                  type="tel"
                  id="mobile"
                  name="mobile"
                  value={formData.mobile}
                  onChange={handleChange}
                  required
                  disabled={isSubmitting}
                  placeholder="(555) 123-4567"
                  className="w-full p-3 rounded-lg bg-white/90 text-gray-800 focus:outline-none focus:ring-2 focus:ring-propertifi-orange disabled:opacity-50"
                />
              </div>
              <div>
                <label htmlFor="message" className="text-white font-semibold block mb-2">
                  Your Message
                </label>
                <textarea
                  id="message"
                  name="message"
                  rows={5}
                  value={formData.message}
                  onChange={handleChange}
                  required
                  disabled={isSubmitting}
                  className="w-full p-3 rounded-lg bg-white/90 text-gray-800 focus:outline-none focus:ring-2 focus:ring-propertifi-orange disabled:opacity-50"
                ></textarea>
              </div>
              <div>
                <button
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-white hover:bg-gray-200 text-propertifi-blue font-bold py-3 px-8 rounded-full transition-colors text-lg disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center"
                >
                  {isSubmitting ? (
                    <>
                      <svg
                        className="animate-spin -ml-1 mr-3 h-5 w-5 text-propertifi-blue"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                      >
                        <circle
                          className="opacity-25"
                          cx="12"
                          cy="12"
                          r="10"
                          stroke="currentColor"
                          strokeWidth="4"
                        ></circle>
                        <path
                          className="opacity-75"
                          fill="currentColor"
                          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                        ></path>
                      </svg>
                      Sending...
                    </>
                  ) : (
                    'Send a Message'
                  )}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Contact;
